# -*- coding: utf-8 -*-
"""OddEvenNumbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe31j9IMZ71hAkU3S3hwdqm8rHlxPhxt
"""

max = int(input("Enter max Number: "))

odd_numbers = []

for i in range(max):
    if i%2 == 1:
        odd_numbers.append(i)
        
print("Odd numbers: ", odd_numbers)

